### ISSUE TITLE
Running fail2ban 0.9.: 

### ISSUE THREAD

**Issue by iain17** [Sean-Der/fail2rest#17]
Dear Sean,
Sorry to have to do this, but it seems that fail2rest doesn't work with the latest fail2ban 0.9.1. I actually went out of my way to get one of the latest versions of fail2ban available on Debian, because fail2rest gave me a message about presistent bans not being available on older version. But afterwards got the following problem:
Unknown opcode 149 () at position 2: '\u0095'
http://puu.sh/cP9G4/f17ae54d50.png

Checking the api request it was actually the first request /api/global/status that reported back with an error:
{"Error":"Unknown opcode 149 () at position 2: '\\u0095'"}

About my version:
:/var/log# fail2ban-client --version
Fail2Ban v0.9.1

Copyright (c) 2004-2008 Cyril Jaquier, 2008- Fail2Ban Contributors
Copyright of modifications held by their respective authors.
Licensed under the GNU General Public License v2 (GPL).

Written by Cyril Jaquier <cyril.jaquier@fail2ban.org>.
Many contributions by Yaroslav O. Halchenko <debian@onerussian.com>.

Before I wanted to send in this issue I actually re-built fail2rest fully from this repository, but that sadly didn't fix it.

Would love to hear your ideas

**Comment by datiti** [comment]
Hi, 
I get the same problem on Debian Wheezy with:
fail2ban 0.9.2-1
golang 1.3.3-1

Running wget on 127.0.0.1:5000/global/ping, i get:
{"Error":"Unknown opcode 149 (�) at position 2: '\\u0095'"}

Running fail2ban-client status, i get:
Status
|- Number of jail:      1
`- Jail list:   sshd

Any idea ?

Thanks and regards
Cyrille

**Comment by Sean-Der** [comment]
Hey @datiti !

thanks for reporting this, I will create a VM tonight with the same environment and see if I can reproduce. 

If I can't I will get together some scripts to try and get debugging information out of your instance.

thanks!

**Comment by datiti** [comment]
Hello,

It should be easy to get the environment: the server on which I am is a
fresh one: Debian testing amd64

Do not hesitate if you need any information.
I'm not used to golang so that I'm not able to investigate myself ;)

Regards
Cyrille

Le mercredi 13 mai 2015, Sean DuBois <notifications@github.com> a écrit :

> Hey @datiti <https://github.com/datiti> !
>
> thanks for reporting this, I will create a VM tonight with the same
> environment and see if I can reproduce.
>
> If I can't I will get together some scripts to try and get debugging
> information out of your instance.
>
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Sean-Der/fail2rest/issues/17#issuecomment-101803145>.
>


-- 
--
M. Cyrille Mescam
4, allée van gogh
78160 marly-le-roi
0675266353

**Comment by Sean-Der** [comment]
Hey @datiti @iain17 sorry it took me so long, but this issue *should* be addressed

I improved the socket handling code in fail2rest, and added the opcodes upstream mentioned in this issue https://github.com/kisielk/og-rek/pull/23

This started showing up reliably in 0.9.3, mind updating everything related to fail2rest and trying again?
