### ISSUE TITLE
fail2rest stop working after fail2ban update from 0.9.1 to 0.9.3

### ISSUE THREAD

**Issue by Fluoo** [Sean-Der/fail2rest#21]
Hello,

I have update my fail2ban from 0.9.1 to 0.9.3 today.

My problem is after this operation fail2rest don't work.
My fail2ban and Fail2rest service are running but I have no answer on the adress of fail2rest It wait and no answer.

I have update Fail2rest to the last version with "go get -u github.com/Sean-Der/fail2rest && go install -v github.com/Sean-Der/fail2rest" but I still have my problem.

Fail2ban is runing correctly : 
fail2ban-client status
Status
|- Number of jail:      8
`- Jail list:   apache-badbots, ckeditor-connector, mail-login-sasl, scripts-setup, sshd, wordpress-config, wordpress-login, wordpress-xmlrpc

I haven't see fail2rest log I don't know if it exist.

Regards.

**Comment by Fluoo** [comment]
Just to add some information : 
downgrade to Fail2Ban 0.9.2 : it's work agian
upgrade to Fail2Ban 0.9.3 : stop working

**Comment by cboisard** [comment]
Same issue with Debian 8

**Comment by Sean-Der** [comment]
I really appreciate your patience @Fluoo @cboisard !

This turned out to be quite the mess, but I am working on it!

https://github.com/Sean-Der/fail2go/commit/d1cc921fc019bce9a779e02d1ad3d9207adb4ea3
https://github.com/Sean-Der/og-rek/commit/b59989dbed521fd95f6eb2aab4047590422eac5b

It would be *really* helpful if you could update your versions of fail2go/fail2rest and tell me what isn't working. This is just a case of Python/fail2ban added new features that I have to implement in the libraries we use to communicate with fail2ban. I should have made a test suite...

**Comment by Fluoo** [comment]
Hello,

I have made "go get -u github.com/Sean-Der/fail2rest && go install -v github.com/Sean-Der/fail2rest" to update to 1.0

I have this response :
# github.com/mattn/go-sqlite3
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte

My problem is still remain.
The fail2rest API doesn't answer.
Failban is woking fine.
Fail2rest service is running.

Do I try yo uninstall and install again fail2rest ?
If you want that I do that please give me the command to uninstall.

Regards.

**Comment by Sean-Der** [comment]
I *think* that doesn't update the libs it depends, just the package you explicitly requested my mistake, try doing.

    go get -u github.com/Sean-Der/fail2rest
    go get -u github.com/Sean-Der/fail2go
    go get -u github.com/Sean-Der/og-rek
    go get -u github.com/mattn/go-sqlite3
    go install -v github.com/Sean-Der/fail2rest

**Comment by Fluoo** [comment]
Hello, 

The problem still after your commands.

Here's the answer for command

root@bunny:/etc/fail2ban# export GOPATH=/home/tools/go
root@bunny:/etc/fail2ban# go get -u github.com/Sean-Der/fail2rest
# github.com/mattn/go-sqlite3
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
root@bunny:/etc/fail2ban# go get -u github.com/Sean-Der/fail2go
# github.com/mattn/go-sqlite3
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
root@bunny:/etc/fail2ban# go get -u github.com/Sean-Der/og-rek
root@bunny:/etc/fail2ban# go get -u github.com/mattn/go-sqlite3
# github.com/mattn/go-sqlite3
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
root@bunny:/etc/fail2ban# go install -v github.com/Sean-Der/fail2rest
github.com/mattn/go-sqlite3
# github.com/mattn/go-sqlite3
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte

**Comment by Sean-Der** [comment]
@Fluoo What version of Golang are you using? This isn't an issue with any of the fail* code, it is with go-sqlite3 https://github.com/mattn/go-sqlite3/issues/245

**Comment by Fluoo** [comment]
My golang version is
go version go1.2.1 linux/amd64

My Server is
Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-74-generic x86_64)

If I need to update golang do you have a repository that I can add so I can Update it with apt-get ?

**Comment by Fluoo** [comment]
I have find a repository and now it works.

For updating golang on ubuntu
add-apt-repository ppa:bcandrea/backports
apt-get update
apt-get dist-upgrade (I think you can make a apt-get upgrade if you prefer)

After that I used the command given above
go get -u github.com/Sean-Der/fail2rest
go get -u github.com/Sean-Der/fail2go
go get -u github.com/Sean-Der/og-rek
go get -u github.com/mattn/go-sqlite3
go install -v github.com/Sean-Der/fail2rest

I do a little
service fail2rest restart
I don't know if it's necessary but I make it

Now my fail2rest answer correctly.

You can close the ticket I haven't close it if @cboisard want to add information.

Thanks a lot @Sean-Der

**Comment by Sean-Der** [comment]
Thanks for using fail2rest @Fluoo! I don't update my fail2ban instance often, so would have been a long time till I caught this.

thanks again :)
