### ISSUE TITLE
whereis fail2rest shows no location

### ISSUE THREAD

**Issue by zenety** [Sean-Der/fail2rest#24]
Installing fail2rest went fine with go1.4. Although when I execute the whereis command nothing is shown. So I have no clue where I should put the configuration file. Any help?

I do have fail2go.a in my pkg folder. But that's it.

**Comment by Sean-Der** [comment]
Hey @zenety did you run a `go install -v github.com/Sean-Der/fail2rest` as well?

If so you should have a binary at `$GOPATH/bin/fail2rest`, try running it from there (and then you can copy that binary anywhere you want)

**Comment by Sean-Der** [comment]
Feel free to reopen @zenety if you are still having issues!

thanks
