### ISSUE TITLE
Can't get fail2rest to run on CentOS

### ISSUE THREAD

**Issue by chris-nc** [Sean-Der/fail2rest#25]
I setup golang and sucessfully created a fail2rest binary but when I start it:

fail2rest --config /etc/fail2rest.json

The command line prompt just hangs and doesn't return.

My config file is the same as the example:

{
  "Addr": "127.0.0.1:5000",
  "Fail2banSocket": "/var/run/fail2ban/fail2ban.sock" 
}

I verified that is the correct location of the fail2bansock.

Any ideas of what to check?

I think the issue may be related to port 5000. It seems to be closed and I haven't been able to open it yet in IPtables.

**Comment by chris-nc** [comment]
I verified port 5000 is open but nothing is listening on it. Can't get the service to run.

**Comment by Sean-Der** [comment]
Hey @chris-nc sorry for the delay
There is no output when failrest starts, so if it hangs that *should* be good.

There was an issue with fail2rest where it would hang with the newest version of fail2ban #21 maybe you are seeing the same behavior, would you mind updating your fail2rest/fail2go (via `go get -u github.com/Sean-Der/fail2rest`) and see if that fixes your issue.

When you say nothing is listening on that port, how did you check/verify that?

thanks!

**Comment by Sean-Der** [comment]
Feel free to reopen @chris-nc if you are still having issues

thanks
