### ISSUE TITLE
fail2rest won't "pong"

### ISSUE THREAD

**Issue by Monstar316** [Sean-Der/fail2rest#26]
imported and installed the fail2rest package through following install instructions on both http://siobud.com/blog/installing-fail2web and https://github.com/Sean-Der/fail2rest.

Neither have allowed fail2rest to "pong" once sending the "ping" command: wget -qO- -- "localhost:5000/global/ping"

Is there something I'm doing wrong? If it makes any odds, I currently have 0.9.3.dev version of fail2ban installed.

**Comment by codecat-** [comment]
Hi @Monstar316 .
Pretty strange. Just checked by instructions and everything works fine. Is there any errors?
Is "ping" only one endpoint which doesn't works for you?

Thanks.

**Comment by Sean-Der** [comment]
Hey @Monstar316 

You were bitten by a bug, but it has been fixed now! Would you mind pulling the newest version of fail2rest/fail2go/ogorek. This can be done via `go get -u github.com/sean-der/fail2rest` it will update fail2rest and all its dependicies. 

The commit that fixed this was https://github.com/kisielk/og-rek/commit/b59989dbed521fd95f6eb2aab4047590422eac5b

If that works for you, would you mind closing out this commit after? thank you!
