### ISSUE TITLE
pong request works status fails

### ISSUE THREAD

**Issue by thavini** [Sean-Der/fail2rest#30]
Pong request works fine but status request failed, is empty.

[""]
centos 7
Fail2ban 0.9.2 
Latest fail2rest.
This way fail2web gives an error:
404 Page Not Found - Couldn't contact fail2rest

nginx is used as webserver. nothing changed in configuration at all. What am i doing wrong.

All look fine if i open /api/jail/ssh the next output is shown.
{"Error":"UnknownJailException: ssh"}
This is as expected.

/api/ results in the 404 not found also. 
should it be redirected or something?

regards, 
Vincent

**Comment by thavini** [comment]
Ticket can be closed. 

{"Error":"UnknownJailException: ssh"} this message is fixed and that resolved the problem for me. 
I was finally able to configure some settings for fail2ban. Didn't think it was necessary to get the fail2rest service to work ;).

Good job with the service. It looks great.

Regards,
Vicnent

**Comment by Sean-Der** [comment]
Thanks for using fail2rest, sorry for the slow response :(

If you have any features you would like to see etc.. always happy to improve it!

**Comment by thavini** [comment]
no problem. i was able to figure it out after configuring fail2ban itself (New server, didn't got the specs at that moment).

maybe give no jails if fail2ban-client status gives no jails. now. fail2web gives the error 404 not found. 

that was a nasty error to figure out the real problem that was not a big problem after all.
